/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BridalAppointment {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'occasion' : string,
  'phone' : string,
  'budget' : string,
}
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'weight' : string,
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
  'material' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, string, bigint, boolean, boolean, string, string],
    bigint
  >,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'bookBridalAppointment' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<BridalAppointment>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isInWishlist' : ActorMethod<[bigint], boolean>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'updateAppointmentStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];